name: iconic
description: "Enhance Flutter projects with stunning icon fonts for a seamless and iconic user experience."
version: 0.1.2
homepage: https://github.com/moha-b/Iconic

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: iconic
      fonts:
        - asset: lib/font/iconic.ttf